config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :chat_rooms, only: %i[new create show index]

  mount ActionCable.server => '/cable'

  root 'chat_rooms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  include Relations::ChatRoom
end

app/models/concerns/relations/chat_room.rb
module Relations::ChatRoom
  extend ActiveSupport::Concern

  included do
    belongs_to :user
    has_many :messages, dependent: :destroy
  end
end

app/models/concerns/relations/message.rb
module Relations::Message
  extend ActiveSupport::Concern

  included do
    belongs_to :user
    belongs_to :chat_room
  end
end

app/models/concerns/relations/user.rb
module Relations::User
  extend ActiveSupport::Concern

  included do
    has_many :chat_rooms, dependent: :destroy
    has_many :messages, dependent: :destroy
  end
end

app/models/concerns/times.rb
module Times
  extend ActiveSupport::Concern

  included do
    def timestamp
      created_at.strftime('%H:%M:%S %d %B %Y')
    end
  end
end

app/models/concerns/validators/message.rb
module Validators::Message
  extend ActiveSupport::Concern

  included do
    validates :body, presence: true, length: { minimum: 2, maximum: 1000 }
  end
end

app/models/concerns/validators/user.rb
module Validators::User
  extend ActiveSupport::Concern

  included do
    validates :email, presence: true, uniqueness: true
  end
end

app/models/message.rb
class Message < ApplicationRecord
  include Validators::Message
  include Relations::Message
  include Times

  after_create_commit { MessageBroadcastJob.perform_later(self) }
end

app/models/user.rb
class User < ApplicationRecord
  include Validators::User
  include Relations::User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  def name
    email.split('@')[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  add_flash_types :success, :warning, :danger, :info
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def index
    @chat_rooms = ChatRoom.all
  end

  def new
    @chat_room = ChatRoom.new
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts={})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end
end

app/views/chat_rooms/_chat_room.html.erb
<li><%= link_to "Enter #{chat_room.title}", chat_room_path(chat_room) %></li>

app/views/chat_rooms/_form.html.erb
<%= form_for @message, url: '#' do |f| %>
  <%= hidden_field_tag 'chat_room_id', @chat_room.id %>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
    <small class="text-muted">From 2 to 1000 characters</small>
  </div>

  <%= f.submit "Post", class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/chat_rooms/index.html.erb
<h1>Chat rooms</h1>

<p class="lead"><%= link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary' %></p>

<ul>
  <%= render @chat_rooms %>
</ul>

app/views/chat_rooms/new.html.erb
<h1>Add chat room</h1>

<%= form_for @chat_room do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
  </div>

  <%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>

app/views/chat_rooms/show.html.erb
<h1><%= @chat_room.title %></h1>

<div id="messages" data-chat-room-id="<%= @chat_room.id %>">
  <%= render @chat_room.messages %>
</div>

<hr>

<%= render 'chat_rooms/form'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ACChat</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <nav class="navbar navbar-inverse bg-primary">
    <%= link_to 'ACChat', root_path, class: 'navbar-brand' %>

    <% if user_signed_in? %>
      <ul class="nav navbar-nav pull-right">
        <li class="nav-item">
          <span class="text-muted">Logged in as <strong><%= current_user.name %></strong></span>
        </li>
        <li class="nav-item active">
          <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      </ul>
    <% end %>
  </nav>



  <div class="container">
    <% flash.each do |key, value| %>
      <div id="flash" class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/messages/_message.html.erb
<div class="card">
  <div class="card-block">
    <div class="row">
      <div class="col-md-1">
        <%= gravatar_for message.user %>
      </div>
      <div class="col-md-11">
        <p class="card-text">
          <span class="text-muted"><%= message.user.name %> at <%= message.timestamp %> says</span><br>
          <%= message.body %>
        </p>
      </div>
    </div>
  </div>
</div>